version: '3.8'

services:
  avito-pvz-service:
      build: .
      container_name: avito-pvz-service
      ports:
        - "8080:8080"
        - "9000:9000"
      environment:
        # енвы подключения к БД
        - DATABASE_PORT=5432
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=password
        - DATABASE_NAME=pvz
        - DATABASE_HOST=db
        # порт сервиса
        - SERVER_PORT=8080
        - METRICS_SERVER_PORT=9000
        - APP_ENV=production
      depends_on:
        db:
            condition: service_healthy
      networks:
        - internal
  
  db:
    image: postgres:13
    container_name: avito-pvz-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pvz
    volumes:
      # "./migrations/init.sql" - путь к миграциям БД
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d pvz'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal: