// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -package reception_closing -typed -destination mock_deps_test.go
//

// Package reception_closing is a generated GoMock package.
package reception_closing

import (
	context "context"
	reflect "reflect"

	model "github.com/inna-maikut/avito-pvz/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MocktrManager is a mock of trManager interface.
type MocktrManager struct {
	ctrl     *gomock.Controller
	recorder *MocktrManagerMockRecorder
	isgomock struct{}
}

// MocktrManagerMockRecorder is the mock recorder for MocktrManager.
type MocktrManagerMockRecorder struct {
	mock *MocktrManager
}

// NewMocktrManager creates a new mock instance.
func NewMocktrManager(ctrl *gomock.Controller) *MocktrManager {
	mock := &MocktrManager{ctrl: ctrl}
	mock.recorder = &MocktrManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrManager) EXPECT() *MocktrManagerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MocktrManager) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MocktrManagerMockRecorder) Do(ctx, fn any) *MocktrManagerDoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MocktrManager)(nil).Do), ctx, fn)
	return &MocktrManagerDoCall{Call: call}
}

// MocktrManagerDoCall wrap *gomock.Call
type MocktrManagerDoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktrManagerDoCall) Return(err error) *MocktrManagerDoCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocktrManagerDoCall) Do(f func(context.Context, func(context.Context) error) error) *MocktrManagerDoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktrManagerDoCall) DoAndReturn(f func(context.Context, func(context.Context) error) error) *MocktrManagerDoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockreceptionRepo is a mock of receptionRepo interface.
type MockreceptionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockreceptionRepoMockRecorder
	isgomock struct{}
}

// MockreceptionRepoMockRecorder is the mock recorder for MockreceptionRepo.
type MockreceptionRepoMockRecorder struct {
	mock *MockreceptionRepo
}

// NewMockreceptionRepo creates a new mock instance.
func NewMockreceptionRepo(ctrl *gomock.Controller) *MockreceptionRepo {
	mock := &MockreceptionRepo{ctrl: ctrl}
	mock.recorder = &MockreceptionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreceptionRepo) EXPECT() *MockreceptionRepoMockRecorder {
	return m.recorder
}

// GetInProgress mocks base method.
func (m *MockreceptionRepo) GetInProgress(ctx context.Context, pvzID model.PVZID) (model.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInProgress", ctx, pvzID)
	ret0, _ := ret[0].(model.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInProgress indicates an expected call of GetInProgress.
func (mr *MockreceptionRepoMockRecorder) GetInProgress(ctx, pvzID any) *MockreceptionRepoGetInProgressCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInProgress", reflect.TypeOf((*MockreceptionRepo)(nil).GetInProgress), ctx, pvzID)
	return &MockreceptionRepoGetInProgressCall{Call: call}
}

// MockreceptionRepoGetInProgressCall wrap *gomock.Call
type MockreceptionRepoGetInProgressCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockreceptionRepoGetInProgressCall) Return(arg0 model.Reception, arg1 error) *MockreceptionRepoGetInProgressCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockreceptionRepoGetInProgressCall) Do(f func(context.Context, model.PVZID) (model.Reception, error)) *MockreceptionRepoGetInProgressCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockreceptionRepoGetInProgressCall) DoAndReturn(f func(context.Context, model.PVZID) (model.Reception, error)) *MockreceptionRepoGetInProgressCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetStatus mocks base method.
func (m *MockreceptionRepo) SetStatus(ctx context.Context, receptionID model.ReceptionID, status model.ReceptionStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, receptionID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockreceptionRepoMockRecorder) SetStatus(ctx, receptionID, status any) *MockreceptionRepoSetStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockreceptionRepo)(nil).SetStatus), ctx, receptionID, status)
	return &MockreceptionRepoSetStatusCall{Call: call}
}

// MockreceptionRepoSetStatusCall wrap *gomock.Call
type MockreceptionRepoSetStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockreceptionRepoSetStatusCall) Return(arg0 error) *MockreceptionRepoSetStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockreceptionRepoSetStatusCall) Do(f func(context.Context, model.ReceptionID, model.ReceptionStatus) error) *MockreceptionRepoSetStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockreceptionRepoSetStatusCall) DoAndReturn(f func(context.Context, model.ReceptionID, model.ReceptionStatus) error) *MockreceptionRepoSetStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockpvzLocker is a mock of pvzLocker interface.
type MockpvzLocker struct {
	ctrl     *gomock.Controller
	recorder *MockpvzLockerMockRecorder
	isgomock struct{}
}

// MockpvzLockerMockRecorder is the mock recorder for MockpvzLocker.
type MockpvzLockerMockRecorder struct {
	mock *MockpvzLocker
}

// NewMockpvzLocker creates a new mock instance.
func NewMockpvzLocker(ctrl *gomock.Controller) *MockpvzLocker {
	mock := &MockpvzLocker{ctrl: ctrl}
	mock.recorder = &MockpvzLockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpvzLocker) EXPECT() *MockpvzLockerMockRecorder {
	return m.recorder
}

// Lock mocks base method.
func (m *MockpvzLocker) Lock(ctx context.Context, pvzID model.PVZID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx, pvzID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lock indicates an expected call of Lock.
func (mr *MockpvzLockerMockRecorder) Lock(ctx, pvzID any) *MockpvzLockerLockCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockpvzLocker)(nil).Lock), ctx, pvzID)
	return &MockpvzLockerLockCall{Call: call}
}

// MockpvzLockerLockCall wrap *gomock.Call
type MockpvzLockerLockCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpvzLockerLockCall) Return(arg0 error) *MockpvzLockerLockCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpvzLockerLockCall) Do(f func(context.Context, model.PVZID) error) *MockpvzLockerLockCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpvzLockerLockCall) DoAndReturn(f func(context.Context, model.PVZID) error) *MockpvzLockerLockCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
